platform :ios, '13.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp

	pod 'Alamofire', '~> 5.4.3'
	pod 'CityPicker'

end
